In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\craft\Desktop\IT_projects\IT_job_market_analyzer\data\raw\jobs.csv")

In [ ]:
df.shape

In [7]:
df.head()

,Unnamed: 0,Category,Workplace,Location,Department,Type
0,0,Business Analyst,Remote,United Kingdom,Operations,Full time
1,1,Business Analyst,Remote,"Makati, Metro Manila, Philippines",Aux HQ,Full time
2,2,Business Analyst,On-site,"Al-Dajeej, Al Farwaniyah Governorate, Kuwait",PWC Technologies,Full time
3,3,Business Analyst,On-site,"London, England, United Kingdom","Consultants, Advisory",Full time
4,4,Business Analyst,Remote,United Kingdom,Operations,Full time

In [3]:
df.columns

Index(['Unnamed: 0', 'Category', 'Workplace', 'Location', 'Department',
       'Type'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1095 non-null   int64
 1   Category    1095 non-null   str
 2   Workplace   1039 non-null   str
 3   Location    1027 non-null   str
 4   Department  929 non-null    str
 5   Type        926 non-null    str
dtypes: int64(1), str(5)
memory usage: 51.5 KB

In [9]:
df.describe()

        Unnamed: 0
count  1095.000000
mean    547.000000
std     316.243577
min       0.000000
25%     273.500000
50%     547.000000
75%     820.500000
max    1094.000000

In [ ]:
df.isna().sum()

Unnamed: 0      0
Category        0
Workplace      56
Location       68
Department    166
Type          169
dtype: int64

In [10]:
((df.isna().sum() / len(df)) * 100).round(2).astype(str) +" %"

Unnamed: 0      0.0 %
Category        0.0 %
Workplace      5.11 %
Location       6.21 %
Department    15.16 %
Type          15.43 %
dtype: str

In [3]:
duplicates = df.duplicated().sum()
print(f"The number of duplicates: {duplicates}")

The number of duplicates: 0

In [5]:
df.nunique()

Unnamed: 0    1095
Category         6
Workplace        5
Location       265
Department     274
Type             6
dtype: int64

In [3]:
for col in ["Workplace", "Category"]:
    print(f"\n{col}")
    print(df[col].unique()[:20])

Workplace
<StringArray>
['Remote', 'On-site', 'Hybrid', nan, 'Hybride', 'Sur cite']
Length: 6, dtype: str

Category
<StringArray>
[  'Business Analyst',              'Cloud',     'Data Scientist',
                 'HR', 'Software Developer',              'UI/UX']
Length: 6, dtype: str

In [4]:
df["Workplace"].value_counts(dropna=False)

Workplace
On-site     461
Remote      413
Hybrid      161
NaN          56
Sur cite      3
Hybride       1
Name: count, dtype: int64

### Workplace column inspection

The `Workplace` column contains both English and French category names:

- `Hybrid` and `Hybride`
- `On-site` and `Sur cite`

The records with `Sur cite` are located in Québec and contain other French-language fields (`Développement Logiciel`, `Temps plein`), suggesting that these values are localized versions of existing workplace categories.

These categories will be standardized during the data cleaning stage.

In [11]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 1095
Columns: 6